# Generated by Django 5.2.11 on 2026-02-27 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='portfolio.portfolio'),
        ),
        migrations.DeleteModel(
            name='PortfolioStock',
        ),
    ]
