# Generated by Django 6.0.2 on 2026-03-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_stock_portfolio_delete_portfoliostock'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='type',
            field=models.CharField(default='standard', max_length=50),
        ),
    ]
