# Generated by Django 5.2.11 on 2026-02-27 07:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pe_ratio', models.FloatField()),
                ('discount_level', models.CharField(max_length=50)),
                ('opportunity_score', models.FloatField()),
                ('graph_data', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='portfolio.stock')),
            ],
        ),
    ]
